const tasksobject = {
  tasks: [
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "Hello World!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is a description",
      task: 'Få datorn att skriva ut "Hello World!"',
      hint: "this is the hint",
      answer: "hello world!",
      facitcheck: true,
      complete: false,
    },
    {
      description: "this is the second description",
      task: "Be datorn räkna ut 520+380 och skriva ut resultatet",
      hint: "Tänk på att du kan koppla ihop olika typer av block för att få ut svaret!",
      answer: "900",
      facitcheck: true,
      complete: false,
    },
  ],
};
